name: thematic compliance CI
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Compliance
    dependsOn: []
    jobs:
      - job: ComplianceJob
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            fetchDepth: 1

          - task: CredScan@3
            inputs:
              outputFormat: sarif
              debugMode: false
          - task: ComponentGovernanceComponentDetection@0
            inputs:
              scanType: 'Register'
              verbosity: 'Verbose'
              alertWarningLevel: 'High'
          - task: PublishSecurityAnalysisLogs@3
            inputs:
              ArtifactName: 'CodeAnalysisLogs'
              ArtifactType: 'Container'