pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x

  - task: npmAuthenticate@0
    displayName: 'npm Authenticate .npmrc'
    inputs:
      workingFile: .npmrc

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: 'Use Yarn 1.22.4'
    inputs:
      versionSpec: 1.22.4

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: 'Yarn '

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@2
    displayName: 'Yarn CI'
    inputs:
      Arguments: ci

  - task: AzureRmWebAppDeployment@3
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    displayName: 'Azure App Service Deploy: essex-thematic'
    inputs:
      azureSubscription: 'Project Essex (d5c2c202-066a-45d3-ace1-e5a8e167a7b9)'
      WebAppName: essex-thematic
      Package: '$(System.DefaultWorkingDirectory)/packages/webapp/build'

  - task: ComponentGovernanceComponentDetection@0
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'

  - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
    displayName: 'Run CredScan'
    inputs:
      toolVersion: 'latest'
      outputFormat: sarif
      debugMode: false

  - task: PublishSecurityAnalysisLogs@3
    inputs:
      ArtifactName: 'CodeAnalysisLogs'
      ArtifactType: 'Container'