name: gh-pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:

    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Use Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - run: yarn install
      name: Install dependencies

    - run: yarn build
      name: Build libs

    - run: yarn bundle
      name: Bundle webapp
    
    - name: Deploy static site
      uses: peaceiris/actions-gh-pages@v3.6.4
      env:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./packages/webapp/build
