name: gh-pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: yarn install
        name: Install dependencies

      - run: 'yarn build:'
        name: Build libs

      - run: 'yarn bundle:'
        name: Bundle webapp

      - name: Deploy static site
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/webapp/build
          CLEAN: true
